language: generic

python: 3.6

cache:
  ccache: true

addons: {apt: {sources: [ ubuntu-toolchain-r-test ]}}
env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1
    - BUILD_SANITIZE_MEMORY=0
    - BUILD_DIR=Build
    - BUILD_TYPE='Release'
    - JOBS=2
    - PATH=$HOME/.local/bin:$PATH
    - SCRIPTS_BASE_DIR=${TRAVIS_BUILD_DIR}/ci/travis
    - SCRIPTS_STAGE_DIR=${CI_BASE_DIR}/$(echo "$a" | tr '[:upper:]' '[:lower:]')
    - SCRIPTS_SHARED_DIR=${SCRIPTS_BASE_DIR}/shared
    - PKG_DIR=${TRAVIS_BUILD_DIR}/package
    - SHARE_DIR=${TRAVIS_BUILD_DIR}/share
    - 

git:
  depth: 1

branches:
  only:
    - master
    - develop
    - ci
    - /^v.*$/

os_templates:
  - &linux
    os: linux
    dist: xenial

  - &linux_gcc6
    <<: *linux
    addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [g++-6] } }
    env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  
  - &linux_gcc7
    <<: *linux
    addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [g++-7] }}
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - &linux_clang4
    <<: *linux
    addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [clang-4.0] }}
    env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

  - &linux_clang5
    <<: *linux
    addons: { apt: { sources: [ ubuntu-toolchain-r-test ], packages: [clang-5.0] }}
    env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - &osx_xcode9
    os: osx
    osx_image: xcode9

  - &osx_xcode94
    <<: *osx_xcode9
    osx_image: xcode9.4

  - &osx_xcode101
    <<: *osx_xcode9
    osx_image: xcode10.1

stage_templates:
  - &default_stage
    install: 
      - source ${SCRIPTS_STAGE_DIR}/install.sh
    before_script: 
      - source ${SCRIPTS_SHARED_DIR}/before_script.sh
    script: 
      - ${SCRIPTS_STAGE_DIR}/script.sh

  - &smoke_stage
    after_success:
      - source ${SCRIPTS_SHARED_DIR}/aws-init.sh
      - source ${SCRIPTS_STAGE_DIR}/pack.sh
      - source ${SCRIPTS_SHARED_DIR}/aws-sync.sh

  - &build_stage
    <<: *default_stage

  - &deploy_stage
    <<: *default_stage         
    git:
      depth: 1
      submodules: false
    before_script:
    script:
    before_deploy:
      - source ${SCRIPTS_SHARED_DIR}/aws-init.sh
      - source ${SCRIPTS_SHARED_DIR}/aws-sync.sh
    after_deploy:
      - source ${SCRIPTS_SHARED_DIR}/aws-clean.sh

  - &docs_stage
    <<: *default_stage
    git:
      depth: 1
      submodules: false
    # after_success:
    #   - source ${SCRIPTS_STAGE_DIR}/pack.sh
    #   - source ${SCRIPTS_SHARED_DIR}/aws-sync.sh

  
# stages:
#   - smoke
#   - test
#   - name: documentation
#     if: branch = master
#   - deploy

jobs:
  include: 
    # - stage: smoke
    #   <<: *linux_gcc7
    #   install: 
    #     - source ./ci/travis/smoke/install.sh
    #   before_script:
    #     - source ${SCRIPTS_SHARED_DIR}/before_script.sh
    #   script: 
    #     - ./ci/travis/smoke/script.sh

    # - stage: smoke
    #   <<: *linux_clang5
    #   <<: *smoke_stage

    # - stage: smoke
    #   <<: *osx_xcode101
    #   <<: *smoke_stage

    # - stage: test
    #   <<: *linux_gcc6
    #   <<: *build_stage

    # - stage: test
    #   <<: *linux_gcc7
    #   <<: *build_stage
      
    # - stage: test
    #   <<: *linux_clang4
    #   <<: *build_stage

    # - stage: test
    #   <<: *linux_clang5
    #   <<: *build_stage
    
    # - stage: test
    #   <<: *osx_xcode9
    #   <<: *build_stage

    # - stage: test
    #   <<: *osx_xcode94
    #   <<: *build_stage

    - stage: documentation
      <<: *linux
      addons: { apt: { packages: [doxygen] }}
      <<: *docs_stage

    # - stage: deploy
    #   <<: *linux
    #   <<: *deploy_stage
    #   deploy:
    #     - provider: releases
    #       skip-cleanup: true
    #       api_key: $GITHUB_TOKEN
    #       file_glob: true
    #       file: 
    #         - share/zacc.*.zip
    #       draft: true  
    #       on:
    #         all_branches: true
    #         tags: true
    #     - provider: pages
    #       skip-cleanup: true
    #       github-token: $GITHUB_TOKEN
    #       local-dir: share/doc
    #       on:
    #         branch: master