language: generic
sudo: true
dist: trusty

cache:
  ccache: true
  apt: true

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1

branches:
  except:
  - gh-pages

matrix:
  include:

    # 1/ Linux Clang Builds
    - os: linux
      addons:
        apt:
          sources: &sources
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - python3-pip
      env: BUILD_TYPE='Release' CXX=clang++-3.9 CC=clang-3.9

    - os: linux
      addons:
        apt:
          sources: *sources
          packages:
           - clang-4.0
           - python3-pip
      env: BUILD_TYPE='Release' CXX=clang++-4.0 CC=clang-4.0

    # 2/ Linux GCC Builds
    - os: linux
      addons: &gcc5
        apt:
          sources: &sources
          packages:
            - g++-5
            - python3-pip
      env: BUILD_TYPE='Release' CXX=g++-5 CC=gcc-5

    - os: linux
      addons: &gcc6
        apt:
          sources: &sources
          packages:
            - g++-6
            - python3-pip
      env: BUILD_TYPE='Release' CXX=g++-6 CC=gcc-6


    # 3/ OSX Clang Builds
#    - os: osx
#      osx_image: xcode6.4
#      compiler: clang
#      env: COMPILER='ccache clang++' BUILD_TYPE='Debug'
#
#    - os: osx
#      osx_image: xcode6.4
#      compiler: clang
#      env: COMPILER='ccache clang++' BUILD_TYPE='Release'


# disable osx for now. Need to test & adapt on a real mac.
#    - os: osx
#      osx_image: xcode7
#      compiler: clang
#      env: COMPILER='ccache clang++' BUILD_TYPE='Debug'
#
#    - os: osx
#      osx_image: xcode7
#      compiler: clang
#      env: COMPILER='ccache clang++' BUILD_TYPE='Release'


install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      sudo brew install cmake ccache
    fi
  - sudo pip3 install yasha
before_script:
  #- export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H../zacc -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd Build

script:
  - make -j 2 && make zacc.tests.all && ctest