language: cpp
sudo: false
dist: trusty

python:
 - "3.3"

cache:
  ccache: true
  apt: true

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1
    - BUILD_SANITIZE_MEMORY=0
    - BUILD_DIR=Build
git:
  depth: 1

branches:
  only:
  - master
  - develop

matrix:
  include:

    # OSX Clang Builds
#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      language: generic
#      env: COMPILER=c++ BUILD_TYPE='Release' CXX=c++ CC=cc

    - os: osx
      osx_image: xcode9
      compiler: clang
      language: generic
      env: COMPILER=c++ BUILD_TYPE='Release' CXX=c++ CC=cc RELEASE_BUILDER=1 DOC_BUILDER=1 RELEASE_NAME="$BRANCH_$TRAVIS_OS_NAME"

    # Linux Clang Builds
    - os: linux
      compiler: clang
      addons: &addons
        apt:
          sources: &sources
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            #- clang-5.0
            - g++-5
            - g++-6
            - g++-7
      env: COMPILER=clang++-4.0 BUILD_TYPE='Release' CXX=clang++-4.0 CC=clang-4.0

#    - os: linux
#      compiler: clang
#      addons: *addons
#      env: COMPILER=clang++-5.0 BUILD_TYPE='Release' CXX=clang++-5.0 CC=clang-5.0

    # Linux GCC Builds
#    - os: linux
#      compiler: gcc
#      addons: *addons
#      env: COMPILER=g++-5 BUILD_TYPE='Release' CXX=g++-5 CC=gcc-5

    - os: linux
      compiler: gcc
      addons: *addons
      env: COMPILER=g++-6 BUILD_TYPE='Release' CXX=g++-6 CC=gcc-6

    - os: linux
      compiler: gcc
      addons: *addons
      env: COMPILER=g++-7 BUILD_TYPE='Release' CXX=g++-7 CC=gcc-7 RELEASE_BUILDER=1 RELEASE_NAME="${BRANCH}_${TRAVIS_OS_NAME}"

before_install:
  - travis_retry ./ci/setup-environment.sh
install:
  - travis_retry ./ci/setup-dependencies.sh
before_script:
  - ./ci/prepare-build.sh
script:
  - ./ci/run-build.sh
  - ./ci/run-test.sh
after_success:
  - ./ci/run-build-documentation.sh
  - ./ci/setup-ssh.sh

before_deploy:
  - ./ci/run-pack-documentation.sh
  - ./ci/run-pack-release.sh

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/docs/html
    on:
      branch: master
      condition: "$DOC_BUILDER = 1"

  - provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN
    #secure: "UGy0FpkUxiMw334ZMvCbreNCRbn1WuRyONTXJtAfGF2cX0HCJ/QHlqgwy5zBi+yUwi79IDtbb2Pr2tvObaK5WL/5NrTikdAoYebO0gzSSd2BIHmniyQsuHEzOciUC0AQxg4Q+TpZaKK8oTRS7NNMN+w7ks23fq7DH6aJOQtiBBHKLotNyKGVZeOgDcpzJD5F9pv39dbumQ9BsfmLn/PMgKHwppKp0E46DCSsSHYKr3XnZfC9SBZAAxICkSEQ1UPN3Dq8lUzry/yTXoLW77ftfK9sAqrCgti39oavJPsgbTEJ/pP0TugxjKwNTKGPdx19439sThsLVi0YQ3hu2vIHfiOUv/I9aN/JsJjkC+pO4kAItwAsVDfq3PVln2E03qn84jFUt8D1lhK36r49dj6bJ4KFXkY3Otr+FEHHE+pf0xugYVxQfbta7H0hTd3UsGrLMCGbzYB30fLKXRFDsGCpoCMcbnAAn3J7LixBMSFxiwZdcriNkbVTODMkOZehDooW6WDp4H1K0S/26Q5G3wjiy48Lwq0s6AbFR2tF33OiXQ00ysPOE36LSun+E278wympUe6BY7T0tzgCfMbivehNs9uyqGct4fDLMmjb4ak3NKnnV/ivORHFD6Gkrb4Uyq3iR2pEM854zjz+4fPI6uw6iZiDnceaox0KawCFMTKirn8="
    file_glob: true
    file: ${TRAVIS_BUILD_DIR}/${RELEASE_NAME}.zip
    on:
      branch: master
      tags: true
      condition: "$RELEASE_BUILDER = 1"

  - provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN
    #  secure: "UGy0FpkUxiMw334ZMvCbreNCRbn1WuRyONTXJtAfGF2cX0HCJ/QHlqgwy5zBi+yUwi79IDtbb2Pr2tvObaK5WL/5NrTikdAoYebO0gzSSd2BIHmniyQsuHEzOciUC0AQxg4Q+TpZaKK8oTRS7NNMN+w7ks23fq7DH6aJOQtiBBHKLotNyKGVZeOgDcpzJD5F9pv39dbumQ9BsfmLn/PMgKHwppKp0E46DCSsSHYKr3XnZfC9SBZAAxICkSEQ1UPN3Dq8lUzry/yTXoLW77ftfK9sAqrCgti39oavJPsgbTEJ/pP0TugxjKwNTKGPdx19439sThsLVi0YQ3hu2vIHfiOUv/I9aN/JsJjkC+pO4kAItwAsVDfq3PVln2E03qn84jFUt8D1lhK36r49dj6bJ4KFXkY3Otr+FEHHE+pf0xugYVxQfbta7H0hTd3UsGrLMCGbzYB30fLKXRFDsGCpoCMcbnAAn3J7LixBMSFxiwZdcriNkbVTODMkOZehDooW6WDp4H1K0S/26Q5G3wjiy48Lwq0s6AbFR2tF33OiXQ00ysPOE36LSun+E278wympUe6BY7T0tzgCfMbivehNs9uyqGct4fDLMmjb4ak3NKnnV/ivORHFD6Gkrb4Uyq3iR2pEM854zjz+4fPI6uw6iZiDnceaox0KawCFMTKirn8="
    file_glob: true
    file: ${TRAVIS_BUILD_DIR}/${RELEASE_NAME}.zip
    on:
      branch: develop
      condition: "$RELEASE_BUILDER = 1"