version: '1.0.{build}'
os: Visual Studio 2015
init: []
install: []

build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- git submodule update --init --recursive
- cmake . -G "Visual Studio 14 2015 Win64"
- cmake --build . --config Release
test_script:
- ctest -C Release -V