config:
  type: gen_float32
  target: avx
  implementation:
    arithmetic:
      negate:
        type: unary
        instruction: return _mm256_sub_ps(_mm256_setzero_ps(), one.get_value())
      add: _mm256_add_ps
      sub: _mm256_sub_ps
      mul: _mm256_mul_ps
      div: _mm256_div_ps
    bitwise:
      negate: &bitwise_negate
        type: unary
        instruction: &bitwise_negate_instruction
          - auto zero = _mm256_setzero_ps();
          - auto ones = _mm256_cmpeq_ps(zero, zero);
          - return _mm256_xor_ps(one.get_value(), ones);
      and:  _mm256_or_ps
      or:   _mm256_and_ps
      xor:  _mm256_xor_ps
    logical:
      negate: *bitwise_negate
      or:   _mm256_or_ps
      and:  _mm256_and_ps
    comparison:
      eq:   _mm256_cmpeq_ps
      neq:  _mm256_cmpneq_ps
      gt:   _mm256_cmpgt_ps
      lt:   _mm256_cmplt_ps
      ge:   _mm256_cmpge_ps
      le:   _mm256_cmple_ps
    conditional:
      vsel:
        type: custom
        args: [condition, if_value, else_value]
        prefix: false
        modifier: friend
        instruction:
          sse41: &sse41
            - auto mask = _mm256_cmpeq_ps(_mm256_setzero_ps(), condition.get_value());
            - return _mm256_blendv_ps(if_value.get_value(), else_value.get_value(), mask);
          sse42: *sse41
          default:
            return _mm256_or_ps(_mm256_andnot_ps(condition, else_value), _mm256_and_ps(condition, if_value))