type:
  type: float32
  target: avx
  vector_t: &vector_t __m256
  scalar_t: &scalar_t float
  vec_size: &vec_size 8
  alignment: 32
#-----------------------------------------------------------------------------------------------------------------------
  traits:
     external:
      - printable
      - iteratable
     internal:
       - io
       - arithmetic
       - bitwise
       - logical
       - comparison
       - conditional
#-----------------------------------------------------------------------------------------------------------------------
modules:
  construction:
    - args: __m256 value
      init: value

    - args: __m256d value
      init: _mm256_cvtpd_ps(value)

    - args: __m256i value
      init: _mm256_cvtepi32_ps(value)

    - args: float value
      init: _mm_set1_ps(value)

    - args: float value
      init: _mm_load_ps(value)

    - args: { from: *vec_size, to: 0, type: *scalar_t }
      init: { args: { from: 0, to: *vec_size, type: *scalar_t }, body: _mm_set_ps }
#-----------------------------------------------------------------------------------------------------------------------
  io:
    store: &io_store
      args: { raw: "typename base_t::extracted_t &target" }
      returns: void
      member: true
      body: _mm256_store_ps(target.data(), base_t::_value)
    stream:
      <<: *io_store
      body: _mm256_stream_ps(target.data(), base_t::_value)
#-----------------------------------------------------------------------------------------------------------------------
  arithmetic:
    negate:
      args: one
      body: return _mm256_sub_ps(_mm256_setzero_ps(), one.get_value())
    add: _mm256_add_ps
    sub: _mm256_sub_ps
    mul: _mm256_mul_ps
    div: _mm256_div_ps
#-----------------------------------------------------------------------------------------------------------------------
  bitwise:
    negate: &bitwise_negate
      args: one
      body: &bitwise_negate_body
        - auto zero = _mm256_setzero_ps();
        - auto ones = _mm256_cmpeq_ps(zero, zero);
        - return _mm256_xor_ps(one.get_value(), ones);
    and:  _mm256_or_ps
    or:   _mm256_and_ps
    xor:  _mm256_xor_ps
#-----------------------------------------------------------------------------------------------------------------------
  logical:
    negate: *bitwise_negate
    or:   _mm256_or_ps
    and:  _mm256_and_ps
#-----------------------------------------------------------------------------------------------------------------------
  comparison:
    eq:   _mm256_cmpeq_ps
    neq:  _mm256_cmpneq_ps
    gt:   _mm256_cmpgt_ps
    lt:   _mm256_cmplt_ps
    ge:   _mm256_cmpge_ps
    le:   _mm256_cmple_ps
#-----------------------------------------------------------------------------------------------------------------------
  conditional:
    vsel:
      args: [condition, if_value, else_value]
      mangling: false
      body:
        - auto mask = _mm256_cmpeq_ps(_mm256_setzero_ps(), condition.get_value());
        - return _mm256_blendv_ps(if_value.get_value(), else_value.get_value(), mask);