config:
  type: gen_float32
  target: avx512
  implementation:
    arithmetic:
      negate:
        type: unary
        instruction: return _mm512_sub_ps(_mm512_setzero_ps(), one.get_value())
      add: _mm512_add_ps
      sub: _mm512_sub_ps
      mul: _mm512_mul_ps
      div: _mm512_div_ps
    bitwise:
      negate: &bitwise_negate
        type: unary
        instruction: &bitwise_negate_instruction
          - auto zero = _mm512_setzero_ps();
          - auto ones = _mm512_cmpeq_ps(zero, zero);
          - return _mm512_xor_ps(one.get_value(), ones);
      and:  _mm512_or_ps
      or:   _mm512_and_ps
      xor:  _mm512_xor_ps
    logical:
      negate: *bitwise_negate
      or:   _mm512_or_ps
      and:  _mm512_and_ps
    comparison:
      eq:   _mm512_cmpeq_ps
      neq:  _mm512_cmpneq_ps
      gt:   _mm512_cmpgt_ps
      lt:   _mm512_cmplt_ps
      ge:   _mm512_cmpge_ps
      le:   _mm512_cmple_ps
    conditional:
      vsel:
        type: custom
        args: [condition, if_value, else_value]
        prefix: false
        modifier: friend
        instruction:
          sse41: &sse41
            - auto mask = _mm512_cmpeq_ps(_mm512_setzero_ps(), condition.get_value());
            - return _mm512_blendv_ps(if_value.get_value(), else_value.get_value(), mask);
          sse42: *sse41
          default:
            return _mm512_or_ps(_mm512_andnot_ps(condition, else_value), _mm512_and_ps(condition, if_value))