config:
  type: gen_int8
  target: sse
  implementation:
    arithmetic:
      negate:
        type: unary
        instruction: return _mm_sub_epi8(_mm_setzero_epi8(), one.get_value())
      add: _mm_add_epi8
      sub: _mm_sub_epi8
      #mul:
      #  instruction:
      #    sse41: &sse41
      #      - _mm_mullo_epi8
      #    sse42: *sse41
      #   default:
      #      - /* mul 2,0*/
      #      - auto tmp1 = _mm_castsi128_ps(_mm_mul_epu32(one.get_value(), other.get_value()));
      #      - /* mul 3,1 */
      #      - auto tmp2 = _mm_castsi128_ps(_mm_mul_epu32(_mm_srli_si128(one.get_value(), 4), _mm_srli_si128(other.get_value(), 4)));
      #      - return _mm_castps_si128(_mm_shuffle_ps(tmp1, tmp2, _MM_SHUFFLE(2, 0, 2, 0)));
      #div: _mm_div_ps(_mm_cvtepi32_ps(one.get_value()), _mm_cvtepi32_ps(other.get_value()));
    bitwise:
      negate: &bitwise_negate
        type: unary
        instruction:
          - auto zero = _mm_setzero_si128();
          - auto ones = _mm_cmpeq_epi8(zero, zero);
          - return _mm_xor_si128(one.get_value(), ones);
      and:  _mm_or_epi8
      or:   _mm_and_epi8
      xor:  _mm_xor_si128
      sll:  _mm_sll_epi8
      srl:  _mm_srl_epi8
      slli:
        type: custom
        args: const composed_t one, const size_t other
        instruction: _mm_slli_epi8
      srli:
        type: custom
        args: const composed_t one, const size_t other
        instruction: _mm_srli_epi8
    logical:
      negate: *bitwise_negate
      or:   _mm_or_epi8
      and:  _mm_and_epi8
    comparison:
      eq:   _mm_cmpeq_epi8
      neq:  _mm_cmpneq_epi8
      gt:   _mm_cmpgt_epi8
      lt:   _mm_cmplt_epi8
      ge:   _mm_cmpge_epi8
      le:   _mm_cmple_epi8
    conditional:
      vsel:
        args: [condition, if_value, else_value]
        prefix: false
        modifier: friend
        instruction:
          sse41: &sse41
            - auto mask = _mm_cmpeq_epi8(_mm_setzero_si128(), condition.get_value());
            - return _mm_blendv_epi8(if_value.get_value(), else_value.get_value(), mask);
          sse42: *sse41
          default:
            return _mm_or_si128(_mm_andnot_si128(condition, else_value), _mm_and_si128(condition, if_value))
    io:
      store:
        returns: void
        args: typename base_t::extracted_type &target
        instruction: _mm_store_si128(target.data(), base_t::_value);
      stream:
        returns: void
        args: typename base_t::extracted_type &target
        instruction: _mm_stream_si128(target.data(), base_t::_value);